{% set name = "pynisher" %}
{% set version = "1.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0642911415809ec90836b06908ef7412a85c20cc9e0818919fb59b6254ec407e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - psutil
    - python >=3.6
    - typing_extensions
    - pywin32-on-windows
    # allows us to stay noarch

test:
  imports:
    - pynisher
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/automl/pynisher
  summary: A small Python library to limit the resources used by a function by executing it inside a subprocess.
  description: |
    The pynisher is a little module intended to limit a functions resources. It starts a new process, sets the desired limits,
    and executes the function inside it. In the end, it returns the function return value. If, for any reason,
    the function call is not successful, None is returned.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/automl/pynisher

extra:
  recipe-maintainers:
    - BastianZim
    - mfeurer
